openapi: "3.0.2"
info:
  title: GO_SVC_TEMPLATE RESTful(ish)Api
  version: "1.0"
  description: The API for GO_SVC_TEMPLATE.
servers:
  - url: https://go-svc-template-dns.local/api/v1
    description: GO_SVC_TEMPLATE RESTful(ish)Api

tags:
  - name: "Accounts"
    description: "Everything about accounts"

components:
  securitySchemes:

    BearerToken:
      type: http
      description: PHDP Access Token
      scheme: bearer
      bearerFormat: JWT

    ServiceAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Service to Service secret authentication

  schemas:
    Account:
      type: object
      properties:
        id:
          type: string
          format: uuid
      required:
        - id

paths:
  /accounts/{id}:
    get:
      tags:
        - "Accounts"
      summary: Get the account of the given id
      parameters:
        - name: id
          in: path
          required: true
          description: id of the requested account
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: OK, if the account was found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        "404":
          description: NOT FOUND, if the consent was not found
